config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  root 'static_pages#home'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook, :twitter]

    def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
      end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
	def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

   def twitter
        @user = User.from_omniauth(request.env["omniauth.auth"])
        
         if @user.persisted?
            sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
            set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
         else
           session["devise.facebook_data"] = request.env["omniauth.auth"]
           redirect_to new_user_registration_url
        end
   end

    def failure
      redirect_to root_path
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
   
  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def resource_class
    devise_mapping.to
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Votester", '#', id: "logo" %><i class="fa fa-caret-square-o-up" style="color:green;"></i><i class="fa fa-caret-square-o-down" style="color:red;"></i>
        <nav>
          <ul class="nav navbar-nav navbar-right" style="margin-top:-40px;">
          <% if user_signed_in? %>
            <li>
              <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
            </li>
            <% else %>
              <li>
                <%= link_to "Log in", '#',  "data-target" => "#myModal2", "data-toggle" => "modal", "type" => "button"  %>
              </li>
              <li>
                <%= link_to "Sign up", '#',  "data-target" => "#myModal", "data-toggle" => "modal", "type" => "button"  %>
              </li>
          <% end %>
          </ul>
        </nav>
      </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoBomb</title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
     <%= render 'layouts/header' %>

   


    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/static_pages/home.html.erb
<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
	<div class="modal-dialog">

		<!-- Modal content-->
		<div class="modal-content">
			<button type="button" class="close" data-dismiss="modal">&times;</button>
			<div class="sign">
				<h2>Sign up</h2>
				<div class="form-group">
					<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
					<%= devise_error_messages! %>

					<div class="field">
						<%= f.label :email %><br />
						<%= f.email_field :email, autofocus: true, class: 'form-control' %>
					</div>

					<div class="field">
						<%= f.label :password %>
						<% if @minimum_password_length %>
						<em>(<%= @minimum_password_length %> characters minimum)</em>
						<% end %><br />
						<%= f.password_field :password, autocomplete: "off" , class: 'form-control'%>
					</div>

					<div class="field">
						<%= f.label :password_confirmation %><br />
						<%= f.password_field :password_confirmation, autocomplete: "off", class: 'form-control' %>
					</div>

					<div class="actions">
						<%= f.submit "Sign up", class: "btn btn-primary" %>
					</div>
					<% end %>
				</div>

				<%= render "devise/shared/links" %>
			</div>
		</div>

	</div>
</div>




<!-- Modal -->
<div id="myModal2" class="modal fade" role="dialog">
	<div class="modal-dialog">
		<!-- Modal content-->
		<div class="modal-content">
			<button type="button" class="close" data-dismiss="modal">&times;</button>

			<div class="sign">
				<h2>Log in</h2>
				<div class="form-group">

				<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
				<div class="field">
					<%= f.label :email %><br />
					<%= f.email_field :email, autofocus: true, class: 'form-control' %>
				</div>

				<div class="field">
					<%= f.label :password %><br />
					<%= f.password_field :password, autocomplete: "off", class: 'form-control' %>
				</div>

				<% if devise_mapping.rememberable? -%>
				<div class="field">
					<%= f.check_box :remember_me %>
					<%= f.label :remember_me %>
				</div>
				<% end -%>

				<div class="actions">
					<%= f.submit "Log in", class: "btn btn-primary" %>
				</div>
				<% end %>
			</div>
			

			<%= render "devise/shared/links" %>
          </div>
			
		</div>
	</div>
</div>

app/views/static_pages/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>